### PR TITLE
Switch curly and no-case-declarations to errors

### PR DESCRIPTION
**Pull request by existentialism**
https://github.com/babel/babel/pull/5412#discussion_r104223658

### CODE REVIEW

**Comment by hzoo** [comment]
btw we have 3 other rules on in master, should get in as many as possible before next release

**Comment by loganfsmyth** [comment]
Nice.

Personally, my vote would be to add these to https://github.com/babel/babel/blob/7.0/.eslintrc in a PR alongside the style fixes, then once we're happy, make a PR to this repo. It seems like a pain to slowly accumulate these over here one at a time.

**Comment by hzoo** [comment]
Great idea

**Comment by danez** [comment]
prettier is not doing this:

https://github.com/babel/babylon/pull/390/files#diff-3d279f04a39b1aaba84ac7b20b0f2625L229

**Pull request merged**
