### PR TITLE
Drop style rules

### PR DESCRIPTION
**Pull request by existentialism**
Ref:
https://github.com/babel/babel-loader/pull/409
https://github.com/babel/babel-preset-env/pull/183
https://github.com/babel/babel/pull/5412
https://github.com/babel/babylon/pull/390

Left `max-len` @ 110 for https://github.com/babel/babel/pull/5412#discussion_r104229850

### CODE REVIEW

**Comment by yavorsky** [comment]
Why we are dropping: `arrow-spacing`, `comma-spacing`, `func-call-spacing`, `keyword-spacing` and a few others not related to prettier rules?

**Comment by existentialism** [comment]
Can keep them, but they seem redundant if we're committed to using prettier as it'd handle formatting them?

**Comment by yavorsky** [comment]
Oh, I understand, thanks! I just thought about projects using babel-config, but not using prettier.

**Comment by danez** [comment]
We could also extend https://github.com/prettier/eslint-config-prettier ?
Otherwise 👍

**Pull request merged**
